# Generated by Django 5.1.6 on 2025-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0003_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
